version: '3.8'

services:
  db:
    image: postgres
    container_name: request_tracer_db
    hostname: request_tracer_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: request_tracer_db
    ports:
      - "5432:5432"
    volumes:
      - request_tracer_db_data:/var/lib/postgresql/data

  shield:
    image: shieldsio/shields:server-2025-07-01
    container_name: request_tracer_shield
    hostname: shield
    ports:
      - "8380:80"

volumes:
  request_tracer_db_data:
