spring:
  config:
    import: optional:file:.properties[.properties]
  application:
    name: view-counter
  security:
    oauth2:
      client:
        registration:
          GitHub:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: read:user, user:email
            redirect-uri: ${BASE_URL:{baseUrl}}/login/oauth2/code/{registrationId}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:request_tracer_db}
    username: postgres
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8181}

logging:
  level:
    me.femrek.viewcounter: trace

shieldUrl: ${SHIELD_URL:http://localhost:8380}
